Feature/add csv support
Geta/geta-notfoundhandler pull request #126
Opened 2024-06-26 21:14 UTC by jaymarvels

- Added in csv import support. 
- Added in csv export support
- Utilised csvhelper for heavy lifting (duel licensed so safe to use)
- Tested against a proj running CMS 12.29.0 and commerce 14.12.0

2024-09-25 08:52 UTC, jevgenijsp requested changes
See comments.

The code overall looks Ok, but I found some places that can be cleaned by reducing code duplication.

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Administer.cshtml.cs
> +            var redirects = _redirectsXmlParser.LoadFromStream(ImportFile.OpenReadStream());
This part can be moved into a separate method where you will pass as a parameter interface IRedirectsParser, to clean a bit of code.

`private IActionResult ProcessFile(IRedirectsParser)`

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Administer.cshtml.cs
> +            Message = "The uploaded file is not a valid XML or CSV file. Please upload a valid XML/CSV file.";
This can be moved into a separate method.

`private IAction BuildResponse(string message, CardType cardType)`

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Administer.cshtml.cs
> +
Re-use `BuildResponse(string message, CardType cardType)`

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Administer.cshtml.cs
> +        if (!string.IsNullOrEmpty(TypeId) && TypeId == "xml")
1) Check if typeId is null or empty and return BuildResponse(string message, CardType cardType).
2) Check if the redirects collection has any items; if not, return BuildResponse(string message, CardType cardType).
3) Create two methods, ExportAsXml and ExportAsCsv, and use them in a switch statement.

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler.Admin/Areas/GetaNotFoundHandlerAdmin/Pages/Infrastructure/IFormFileExtensions.cs
> +        public static bool IsCsv(this IFormFile file)
New line

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler/Core/Redirects/RedirectsCsvParser.cs
> +public class RedirectsCsvParser
Add IRedirectsParser interface with `CustomRedirectCollection LoadFromStream(Stream csvContent)` as a method and implement this interface here. Also, add implementation for existing RedirectsXmlParser.

2024-09-25 08:52 UTC, jevgenijsp commented on src/Geta.NotFoundHandler/Geta.NotFoundHandler.csproj
> +  <ItemGroup>
I don't think that we need Models here.

2024-10-01 07:15 UTC, jevgenijsp approved these changes

2024-10-01 07:27 UTC, merged

2024-10-02 18:09 UTC, jaymarvels commented
@jevgenijsp Thanks for doing this, I was slowly getting around to completing. Glad its in the package now.

2024-10-03 05:05 UTC, jevgenijsp commented
@jaymarvels Thanks for contributing! 👏